version: "3.7"

services:
  backend:
    build: ./backend
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/src/ip/server/src
    command: npm run start
    networks:
      -  yolo-ip-network

  client:
    build: ./client
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/src/ip/test-client/src
      - ./client/public:/src/ip/test-client/public
    command: npm run start
    networks:
      - yolo-ip-network

networks:
   yolo-ip-network:
    driver: bridge

    