version: "3.7"

services:
  backend:
    # build: ./backend
    image: chukula/backend:1.0.0
    expose:
      - 5020
    ports:
      - "5020:5020"
    volumes:
      - ./backend/src:/src/ip/server/src
    command: npm run start
    networks:
      -  yolo-ip-network

  client:
    # build: ./client
    image: chukula/client:1.0.0
    expose:
      - 3090
    ports:
      - "3090:3090"
    volumes:
      - ./client/src:/src/ip/test-client/src
      - ./client/public:/src/ip/test-client/public
    command: npm run start
    networks:
      - yolo-ip-network

networks:
   yolo-ip-network:
    driver: bridge

    

