#Using a node alpine image
FROM node:alpine3.18

# setting the working directory
RUN mkdir -p /src/ip/server
WORKDIR /src/ip/server

# Copying the package.json file to the working directory
COPY package*.json /src/ip/server

# Installing the dependencies
RUN npm install --silent

# Copying the resr of the files to the working directory
COPY . /src/ip/server

# Running the app
CMD ["npm", "start"]