apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-yolo-deployment
spec:
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
        - name: client
          image: chukula/client:1.0.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: client-deployment-service
spec:
  type: NodePort
  selector:
    app: yolo-client
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
  type: LoadBalancer
