# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: client-deployemnt
# spec:
#   selector:
#     matchLabels:
#       app: client
#   template:
#     metadata:
#       labels:
#         app: client
#     spec:
#       containers:
#         - name: client
#           image: chukula/client:1.0.0
#           ports:
#             - containerPort: 3000

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: client-deployment-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: client
#   ports:
#     - port: 3000
#       targetPort: 3000



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    appName: yolo
    serverClass : client
    memoryOptimised : "yes"
    component: frontend
  annotations:
    description: "Deployment for frontend application"
spec:
  replicas: 1
  selector:
    matchLabels:
      appName : yolo
      memoryOptimised : "yes" 
      app: yoloclient
      component: frontend
  template:
    metadata:
      labels:
        appName : yolo
        memoryOptimised : "yes"
        app: yoloclient
        component: frontend
    spec:
      containers:
        - name: client
          image: chukula/client:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"              
          env:
            - name: CLIENT_HOST
              value: "yolo-backend-service"
            - name: CLIENT_PORT
              value: "5000"